version: '3.9'

services:
  library-backend:
    container_name: library-backend
    build : .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./core:/app
    ports:
      - "8002:8002"
    environment:
      - DEBUG=True
      - SECRET_KEY="test"
    tty: true