# Generated by Django 4.0 on 2023-02-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_category_book_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(blank=True, null=True, to="books.Author"),
        ),
    ]
