# Generated by Django 4.0 on 2023-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(blank=True, null=True, to="books.Category"),
        ),
    ]
